### ISSUE TITLE
Error on node version installed.  

### ISSUE THREAD

**Issue by aswinme** [D-codE-Hub/Guide-to-Install-Frappe-ERPNext-in-Ubuntu-22.04-LTS#9]
i have installed nvm using> nvm install 14.15.0 but in the bench initialisation step>bench init frappe-bench  i faced the error as shown below.  

error frappe-framework@: The engine "node" is incompatible with this module. Expected version ">=18". Got "14.15.0"
error Found incompatible module.
----------------------------------------------------------------
I  uninstalled sudo -H pip3 uninstall frappe-bench latest version 5.16.4 and installed a specific version using >sudo -H pip3 install frappe-bench==5.2.1 and then ran>bench init frappe-bench  for initialization frappe bench. 
now i get the following error 
Already using interpreter /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/virtualenv.py", line 821, in main
    create_environment(
  File "/usr/local/lib/python3.10/dist-packages/virtualenv.py", line 1106, in create_environment
    install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink)
  File "/usr/local/lib/python3.10/dist-packages/virtualenv.py", line 1666, in install_python
    fix_local_scheme(home_dir, symlink)
  File "/usr/local/lib/python3.10/dist-packages/virtualenv.py", line 1752, in fix_local_scheme
    if sysconfig._get_default_scheme() == "posix_local":
AttributeError: module 'sysconfig' has no attribute '_get_default_scheme'. Did you mean: 'get_default_scheme'?

Getting frappe
$ git clone https://github.com/frappe/frappe.git  --depth 1 --origin upstream
Cloning into 'frappe'...
remote: Enumerating objects: 3219, done.
remote: Counting objects: 100% (3219/3219), done.
remote: Compressing objects: 100% (2837/2837), done.
remote: Total 3219 (delta 419), reused 1757 (delta 281), pack-reused 0
Receiving objects: 100% (3219/3219), 17.19 MiB | 10.62 MiB/s, done.
Resolving deltas: 100% (419/419), done.
[Errno 2] No such file or directory: 'frappe-bench/apps/frappe/setup.py'
ERROR: There was a problem while creating frappe-bench
Do you want to rollback these changes? [Y/n]: ^C
Aborted!
INFO: A newer version of bench is available: 5.2.1 → 5.16.4
--------------------------------------------------------------------------
Is there any compatibility issue with  nvm 14.15.0 ? How to solve it ?
Thanks for support

**Comment by Mood93** [comment]
@aswinme Any luck on this?

**Comment by atc6955** [comment]
I got the same error. 
 
1) Run 
`nvm install 18`

2) remove the old version with
`nvm uninstall 14.15.0` (or whatever version you installed via the script)


3) Now you can successfully run 
`bench init frappe-bench 
cd frappe-bench/
bench start`
